### ISSUE TITLE
scheduler gui doesn't display schedule when one combo

### ISSUE THREAD

**Issue by ngokevin** [thedjpetersen/reggit#4]
When there is only one combination of classes possible from make_schedule.py, the scheduler app does not display the classes on the schedule on hover like it does when there are multiple combinations.

**Comment by ngokevin** [comment]
hi

**Comment by thedjpetersen** [comment]
yo

**Comment by thedjpetersen** [comment]
It was interesting to see how I wrote Javascript 5 years ago...better than today apparently

**Comment by ngokevin** [comment]
lol really. i look back on my python, it was bush league. anyways, this was my first GH issue!
